# -*- coding: utf-8 -*-
"""KLTN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XsXxBxcFWj-0RljQts5HEGNEZVfBe2H5

0. CÀI THƯ VIỆN
=========================
"""

!pip install -qq google-play-scraper
!pip install -qq -U watermark tqdm
!pip install -q "pillow<12"
!pip install -qq underthesea
!pip install -qq scikit-learn
!pip install -qq imbalanced-learn
!pip install -qq wordcloud

"""=========================
1. IMPORT & KIỂM TRA VERSION
=========================
"""

# Commented out IPython magic to ensure Python compatibility.
#Kiểm tra phiên bản thư viện
# %reload_ext watermark
# %watermark -v -p pandas,matplotlib,seaborn,google_play_scraper

import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

from google_play_scraper import app
from google_play_scraper.features.reviews import reviews, Sort

from pygments import highlight
from pygments.lexers import JsonLexer
from pygments.formatters import TerminalFormatter

"""=========================
2. DANH SÁCH APP NGÂN HÀNG
=========================
"""

# Danh sách ứng dụng ngân hàng
APP_PACKAGES = [
    'com.vnpay.bidv',
    'com.vnpay.Agribank3g',
    'com.VCB',
    'com.sacombank.ewallet',
    'com.mbmobile',
    'com.vietinbank.ipay',
    'com.tpb.mb.gprsandroid',
    'vn.com.techcombank.bb.app',
    'com.vnpay.hdbank',
    'mobile.acb.com.vn',
    'vn.com.ocb.awe',
    'vn.com.msb.smartBanking',
]


len(APP_PACKAGES)

"""=========================
3. CRAWL THÔNG TIN APP
=========================
"""

# Thu thập thông tin ứng dụng
app_infos = []

for ap in tqdm(APP_PACKAGES, desc="Crawling app info"):
    info = app(ap, lang="vi", country="vn")
    info.pop("comments", None)
    app_infos.append(info)

app_infos_df = pd.DataFrame(app_infos)
app_infos_df.to_csv("apps_raw.csv", index=False, encoding="utf-8-sig")

# Hàm hiển thị JSON
def print_json(json_object):
    json_str = json.dumps(
        json_object,
        indent=2,
        sort_keys=True,
        default=str
    )
    print(highlight(json_str, JsonLexer(), TerminalFormatter()))

# Hiển thị thông tin ứng dụng đầu tiên
print_json(app_infos[0])

"""=========================
4. HIỂN THỊ ICON APP
=========================
"""

from PIL import Image
import urllib.request

def format_title(title):
    for sep in [":", "-"]:
        if sep in title:
            title = title.split(sep)[0]
    return title[:10]

fig, axs = plt.subplots(2, len(app_infos)//2, figsize=(14, 5))

for i, ax in enumerate(axs.flat):
    ai = app_infos[i]
    img = np.array(Image.open(urllib.request.urlopen(ai["icon"])))
    ax.imshow(img)
    ax.set_title(format_title(ai["title"]))
    ax.axis("off")

plt.show()

app_infos_df = pd.DataFrame(app_infos)
app_infos_df.head(12)

app_infos_df.to_csv('apps.csv', index=False)

"""=========================
5. CRAWL REVIEW (RAW)
=========================
"""

# Crawl reviews
app_reviews = []

for ap in tqdm(APP_PACKAGES, desc="Crawling reviews"):
    try:
        for score in range(1, 6):
            for sort_order in [Sort.MOST_RELEVANT, Sort.NEWEST]:
                data, _ = reviews(
                    ap,
                    lang="vi",
                    country="vn",
                    sort=sort_order,
                    count=200 if score == 3 else 100,
                    filter_score_with=score
                )

                for r in data:
                    r["appId"] = ap
                    r["sortOrder"] = (
                        "most_relevant" if sort_order == Sort.MOST_RELEVANT else "newest"
                    )

                app_reviews.extend(data)

    except Exception as e:
        print(f"Error {ap}: {e}")

print_json(app_reviews[0])

app_reviews_df = pd.DataFrame(app_reviews)
app_reviews_df.shape

app_reviews_df.head(200)

len(app_reviews_df)

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Đường dẫn lưu file (bạn có thể đổi tên thư mục)
SAVE_PATH = "/content/drive/MyDrive/google_play_scraper"

# Tạo thư mục nếu chưa tồn tại
import os
os.makedirs(SAVE_PATH, exist_ok=True)

# Lưu app info
app_infos_df.to_csv(
    f"{SAVE_PATH}/apps_info.csv",
    index=False,
    encoding="utf-8-sig"
)

# Lưu reviews
app_reviews_df.to_csv(
    f"{SAVE_PATH}/apps_reviews.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Đã lưu file CSV vào Google Drive")

# ========================================
# BƯỚC 1: IMPORT THƯ VIỆN
# ========================================
import re
import pandas as pd
import numpy as np
from typing import Dict, List
import os

print("Import thư viện thành công!")


# ========================================
# BƯỚC 2: ĐỊNH NGHĨA CLASS CLEANER
# ========================================
class VietnameseReviewCleaner:
    """
    Bộ xử lý text cho reviews tiếng Việt
    - Chuẩn hóa teencode
    - Sửa viết tắt
    - Loại bỏ icon/emoji
    - Sửa lỗi chính tả phổ biến
    """

    def __init__(self):
        # Từ điển teencode -> chuẩn
        self.teencode_dict = {
            'k': 'không', 'ko': 'không', 'hok': 'không', 'hong': 'không',
            'hem': 'không', 'kg': 'không', 'kh': 'không', 'khong': 'không',
            'dc': 'được', 'đc': 'được', 'dk': 'được', 'đk': 'được',
            'vs': 'với', 'vc': 'với', 'v': 'với',
            'ms': 'mới', 'mik': 'mình', 'mk': 'mình', 'mh': 'mình', 'mjh': 'mình',
            'tui': 'tôi', 'toy': 'tôi', 'toj': 'tôi',
            'bt': 'bình thường', 'bth': 'bình thường',
            'ntn': 'như thế nào', 'sao': 'như thế nào',
            'r': 'rồi', 'rùi': 'rồi', 'rui': 'rồi',
            'ak': 'à', 'ạk': 'ạ', 'nhaa': 'nhé', 'nha': 'nhé',
            'nek': 'nè', 'né': 'nè',
            'cx': 'cũng', 'cug': 'cũng',
            'bik': 'biết', 'bit': 'biết', 'bjt': 'biết',
            'z': 'vậy', 'zay': 'vậy',
            'wa': 'quá', 'qá': 'quá', 'wá': 'quá',
            'j': 'gì', 'zì': 'gì', 'jì': 'gì',
            'chs': 'chưa', 'chx': 'chưa',
            'tks': 'cảm ơn', 'tk': 'cảm ơn', 'thanks': 'cảm ơn',
            'tnks': 'cảm ơn', 'cam on': 'cảm ơn',
            'nc': 'nói chuyện', 'nch': 'nói chuyện',
            'ngta': 'người ta', 'nguoi ta': 'người ta', 'nta': 'người ta',
            'uk': 'ừ', 'uh': 'ừ',
            'oke': 'ok', 'okie': 'ok', 'okee': 'ok',
            'đag': 'đang', 'dg': 'đang', 'dang': 'đang',
            'lm': 'làm', 'lam': 'làm',
            'pk': 'phải', 'fai': 'phải', 'pải': 'phải',
            'xl': 'xin lỗi', 'sr': 'xin lỗi', 'sorry': 'xin lỗi',
            'tl': 'trả lời', 'rep': 'trả lời',
            'ib': 'inbox', 'mess': 'nhắn tin',
            'sd': 'sử dụng', 'xd': 'sử dụng',
            'ng': 'người', 'nguoi': 'người',
            'bn': 'bạn', 'b': 'bạn',
            'mn': 'mọi người', 'ad': 'admin',
            'app': 'ứng dụng', 'ứg dụng': 'ứng dụng', 'ung dung': 'ứng dụng',
        }

        # Từ điển lỗi chính tả phổ biến
        self.typo_dict = {
            'duoc': 'được', 'nhu': 'như', 'chi': 'chỉ',
            'nhung': 'nhưng', 'ma': 'mà', 'thi': 'thì',
            'tai': 'tại', 'lai': 'lại', 'nua': 'nữa',
            'dau': 'đâu', 'khi': 'khi', 'rat': 'rất',
            'tot': 'tốt', 'xau': 'xấu', 'te': 'tệ',
            'hay': 'hay', 'den': 'đến', 'cho': 'cho',
            'chua': 'chưa', 'roi': 'rồi', 'vao': 'vào',
            'xem': 'xem', 'nhan': 'nhận', 'gui': 'gửi',
        }

        # Icon/emoji patterns
        self.emoji_pattern = re.compile(
            "["
            "\U0001F600-\U0001F64F"
            "\U0001F300-\U0001F5FF"
            "\U0001F680-\U0001F6FF"
            "\U0001F1E0-\U0001F1FF"
            "\U00002702-\U000027B0"
            "\U000024C2-\U0001F251"
            "]+",
            flags=re.UNICODE
        )

    def clean_text(self, text: str) -> str:
        """Làm sạch text đầy đủ"""
        if not isinstance(text, str):
            return ""

        text = text.lower()
        text = self.emoji_pattern.sub('', text)
        text = re.sub(r'[^\w\s\.,!?áàảãạăắằẳẵặâấầẩẫậéèẻẽẹêếềểễệíìỉĩịóòỏõọôốồổỗộơớờởỡợúùủũụưứừửữựýỳỷỹỵđ]', ' ', text)
        text = re.sub(r'\s+', ' ', text).strip()
        text = re.sub(r'(.)\1{2,}', r'\1', text)

        words = text.split()
        words = [self.teencode_dict.get(w, w) for w in words]
        text = ' '.join(words)

        words = text.split()
        words = [self.typo_dict.get(w, w) for w in words]
        text = ' '.join(words)

        return ' '.join(text.split())

    def clean_dataframe(self, df: pd.DataFrame, text_column: str = 'content') -> pd.DataFrame:
        """Làm sạch toàn bộ dataframe - TẠO BẢN SAO"""
        df_cleaned = df.copy()
        print(f"Đang làm sạch {len(df_cleaned)} reviews...")
        df_cleaned[f'{text_column}_cleaned'] = df_cleaned[text_column].apply(self.clean_text)

        empty_reviews = df_cleaned[f'{text_column}_cleaned'].str.strip().eq('').sum()
        print(f"Hoàn thành!")
        print(f"Reviews trống: {empty_reviews}")
        print(f"Reviews hợp lệ: {len(df_cleaned) - empty_reviews}")
        return df_cleaned

    def get_stats(self, df: pd.DataFrame, original_col: str = 'content',
                  cleaned_col: str = 'content_cleaned') -> pd.DataFrame:
        """Thống kê trước/sau cleaning"""
        stats = pd.DataFrame({
            'original_length': df[original_col].str.len(),
            'cleaned_length': df[cleaned_col].str.len(),
            'original_words': df[original_col].str.split().str.len(),
            'cleaned_words': df[cleaned_col].str.split().str.len(),
        })

        print("\n" + "="*80)
        print("THỐNG KÊ CLEANING")
        print("="*80)
        print(f"\n Độ dài TB (ký tự): {stats['original_length'].mean():.1f} → {stats['cleaned_length'].mean():.1f}")
        print(f"Số từ TB: {stats['original_words'].mean():.1f} → {stats['cleaned_words'].mean():.1f}")
        print("="*80 + "\n")
        return stats

    def compare_samples(self, df: pd.DataFrame, n: int = 10,
                       original_col: str = 'content',
                       cleaned_col: str = 'content_cleaned'):
        """So sánh mẫu trước/sau cleaning"""
        print("\n" + "="*80)
        print(f"SO SÁNH {n} REVIEWS NGẪU NHIÊN")
        print("="*80 + "\n")

        sample = df.sample(n=min(n, len(df)))

        for idx, row in enumerate(sample.itertuples(), 1):
            original = getattr(row, original_col)
            cleaned = getattr(row, cleaned_col)

            print(f"[{idx}] Review #{row.Index}")
            print("─"*80)
            print(f"TRƯỚC: {original}")
            print(f"SAU:   {cleaned}")

            if original != cleaned:
                diff = len(original) - len(cleaned)
                print(f"Giảm {diff} ký tự")
            print()

        print("="*80 + "\n")


print(" Class VietnameseReviewCleaner đã được định nghĩa!")


# ========================================
# BƯỚC 3: ĐỌC FILE TỪ GOOGLE DRIVE
# ========================================
print("\n" + "="*80)
print(" BƯỚC 3: ĐỌC FILE TỪ GOOGLE DRIVE")
print("="*80 + "\n")

FILE_PATH = '/content/drive/MyDrive/google_play_scraper/apps_reviews.csv'
DRIVE_FOLDER = os.path.dirname(FILE_PATH)

print(f" Folder: {DRIVE_FOLDER}")
print(f" File: {os.path.basename(FILE_PATH)}")

if not os.path.exists(FILE_PATH):
    print(f"\n File không tồn tại: {FILE_PATH}")
    print("\n Tìm file trong Drive...")
    for root, dirs, files in os.walk('/content/drive/MyDrive'):
        for file in files:
            if 'review' in file.lower() and file.endswith('.csv'):
                full_path = os.path.join(root, file)
                size = os.path.getsize(full_path)
                print(f"   • {full_path} ({size/1024:.1f} KB)")
    print("\n Sửa đường dẫn FILE_PATH ở đầu BƯỚC 3")
else:
    print(f" File tồn tại!")

    df_original = pd.read_csv(FILE_PATH)
    print(f"\n Đã đọc file: {os.path.basename(FILE_PATH)}")
    print(f" Tổng số dòng: {len(df_original)}")
    print(f" Các cột: {list(df_original.columns)}")
    print(f"\n Xem 3 dòng đầu:")
    print(df_original.head(3))


# ========================================
# BƯỚC 4-9: CLEAN VÀ LƯU FILE
# ========================================
if 'df_original' in locals():
    print("\n" + "="*80)
    print("BƯỚC 4: CLEAN DATA")
    print("="*80 + "\n")

    cleaner = VietnameseReviewCleaner()
    df_cleaned = cleaner.clean_dataframe(df_original, text_column='content')

    # So sánh mẫu
    cleaner.compare_samples(df_cleaned, n=3)

    # Thống kê
    stats = cleaner.get_stats(df_cleaned)

    # Lưu file
    print("\n" + "="*80)
    print("LƯU FILE")
    print("="*80 + "\n")

    output_cleaned = f'{DRIVE_FOLDER}/reviews_cleaned.csv'
    df_cleaned.to_csv(output_cleaned, index=False, encoding='utf-8-sig')
    print(f"Đã lưu: reviews_cleaned.csv")


# ========================================
# BƯỚC 10: GẮN NHÃN SENTIMENT
# ========================================
if 'df_cleaned' in locals():
    print("\n" + "="*80)
    print("BƯỚC 10: GẮN NHÃN SENTIMENT")
    print("="*80 + "\n")

    if 'score' in df_cleaned.columns:
        print(" Phân loại: 1-3⭐ = TIÊU CỰC | 4-5⭐ = TÍCH CỰC\n")

        df_cleaned['sentiment'] = df_cleaned['score'].apply(
            lambda x: 'negative' if x <= 3 else 'positive'
        )
        df_cleaned['sentiment_vi'] = df_cleaned['score'].apply(
            lambda x: 'tiêu cực' if x <= 3 else 'tích cực'
        )
        df_cleaned['sentiment_label'] = df_cleaned['score'].apply(
            lambda x: 0 if x <= 3 else 1
        )

        print(" Đã gắn nhãn!\n")
        print(" THỐNG KÊ SENTIMENT:")
        print("="*80)

        sentiment_counts = df_cleaned['sentiment_vi'].value_counts()
        total = len(df_cleaned)

        for sentiment, count in sentiment_counts.items():
            percentage = (count / total) * 100
            print(f"   • {sentiment.upper()}: {count:,} ({percentage:.1f}%)")

        print("\n PHÂN BỐ THEO RATING:")
        print("="*80)
        rating_dist = df_cleaned.groupby('score').agg({
            'sentiment_vi': 'first',
            'content': 'count'
        }).rename(columns={'content': 'count'})

        for score, row in rating_dist.iterrows():
            percentage = (row['count'] / total) * 100
            stars = '⭐' * int(score)
            print(f"   {stars} ({score} sao) - {row['sentiment_vi']}: {row['count']:,} ({percentage:.1f}%)")

        print("\n" + "="*80)
    else:
        print("Không tìm thấy cột 'score'")
        print(f"Các cột: {list(df_cleaned.columns)}")
# ========================================
# BƯỚC 10.5: VẼ BIỂU ĐỒ CỘT SENTIMENT
# ========================================
if 'df_cleaned' in locals() and 'sentiment' in df_cleaned.columns:
    print("\n" + "="*80)
    print("VẼ BIỂU ĐỒ CỘT SENTIMENT")
    print("="*80 + "\n")

    # Tạo figure với 2 subplots
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # Biểu đồ 1: Phân bố theo Sentiment (Tích cực/Tiêu cực)
    sentiment_counts = df_cleaned['sentiment_vi'].value_counts()
    colors = ['#ff6b6b', '#51cf66']  # Đỏ cho tiêu cực, xanh cho tích cực

    bars1 = axes[0].bar(sentiment_counts.index, sentiment_counts.values, color=colors, alpha=0.8, edgecolor='black', linewidth=1.5)
    axes[0].set_title('PHÂN BỔ SENTIMENT', fontsize=14, fontweight='bold', pad=15)
    axes[0].set_xlabel('Sentiment', fontsize=12)
    axes[0].set_ylabel('Số lượng reviews', fontsize=12)
    axes[0].grid(axis='y', alpha=0.3, linestyle='--')

    # Thêm số lượng và phần trăm lên trên mỗi cột
    total = len(df_cleaned)
    for bar in bars1:
        height = bar.get_height()
        percentage = (height / total) * 100
        axes[0].text(bar.get_x() + bar.get_width()/2., height,
                    f'{int(height):,}\n({percentage:.1f}%)',
                    ha='center', va='bottom', fontsize=11, fontweight='bold')

    # Biểu đồ 2: Phân bố theo Rating (1-5 sao)
    rating_counts = df_cleaned['score'].value_counts().sort_index()
    colors_rating = ['#e03131', '#f76707', '#fab005', '#74b816', '#20c997']

    bars2 = axes[1].bar(rating_counts.index, rating_counts.values,
                       color=colors_rating, alpha=0.8, edgecolor='black', linewidth=1.5)
    axes[1].set_title('PHÂN BỔ THEO RATING', fontsize=14, fontweight='bold', pad=15)
    axes[1].set_xlabel('Số sao', fontsize=12)
    axes[1].set_ylabel('Số lượng reviews', fontsize=12)
    axes[1].set_xticks([1, 2, 3, 4, 5])
    axes[1].grid(axis='y', alpha=0.3, linestyle='--')

    # Thêm số lượng và phần trăm lên trên mỗi cột
    for bar in bars2:
        height = bar.get_height()
        percentage = (height / total) * 100
        axes[1].text(bar.get_x() + bar.get_width()/2., height,
                    f'{int(height):,}\n({percentage:.1f}%)',
                    ha='center', va='bottom', fontsize=10, fontweight='bold')

    plt.tight_layout()

    # Lưu biểu đồ
    chart_path = f'{DRIVE_FOLDER}/sentiment_distribution.png'
    plt.savefig(chart_path, dpi=300, bbox_inches='tight')
    print(f"Đã lưu biểu đồ: sentiment_distribution.png")

    plt.show()

    print("="*80)

# ========================================
# BƯỚC 11: XEM MẪU & LƯU FILE
# ========================================
if 'df_cleaned' in locals() and 'sentiment' in df_cleaned.columns:
    # Mẫu reviews
    print("\n" + "="*80)
    print("MẪU REVIEWS")
    print("="*80)

    print("\n TIÊU CỰC (3 mẫu):")
    neg_samples = df_cleaned[df_cleaned['sentiment'] == 'negative'].sample(n=min(3, len(df_cleaned[df_cleaned['sentiment'] == 'negative'])))
    for idx, row in enumerate(neg_samples.itertuples(), 1):
        print(f"\n[{idx}] ⭐{row.score} - {row.content_cleaned[:80]}...")

    print("\n\n TÍCH CỰC (3 mẫu):")
    pos_samples = df_cleaned[df_cleaned['sentiment'] == 'positive'].sample(n=min(3, len(df_cleaned[df_cleaned['sentiment'] == 'positive'])))
    for idx, row in enumerate(pos_samples.itertuples(), 1):
        print(f"\n[{idx}] ⭐{row.score} - {row.content_cleaned[:80]}...")

    # Lưu file
    print("\n\n" + "="*80)
    print("LƯU FILE CÓ NHÃN")
    print("="*80 + "\n")

    # File đầy đủ
    output_full = f'{DRIVE_FOLDER}/reviews_with_sentiment.csv'
    df_cleaned.to_csv(output_full, index=False, encoding='utf-8-sig')
    print(f"reviews_with_sentiment.csv")

    # File cho ML
    ml_cols = ['content_cleaned', 'sentiment', 'sentiment_label', 'score']
    output_ml = f'{DRIVE_FOLDER}/reviews_for_ml.csv'
    df_cleaned[[c for c in ml_cols if c in df_cleaned.columns]].to_csv(output_ml, index=False, encoding='utf-8-sig')
    print(f"reviews_for_ml.csv")

    # File phân loại
    df_negative = df_cleaned[df_cleaned['sentiment'] == 'negative']
    df_positive = df_cleaned[df_cleaned['sentiment'] == 'positive']

    df_negative.to_csv(f'{DRIVE_FOLDER}/reviews_negative.csv', index=False, encoding='utf-8-sig')
    df_positive.to_csv(f'{DRIVE_FOLDER}/reviews_positive.csv', index=False, encoding='utf-8-sig')

    print(f"reviews_negative.csv ({len(df_negative)} reviews)")
    print(f"reviews_positive.csv ({len(df_positive)} reviews)")

    # Tóm tắt
    print("\n" + "="*80)
    print("TÓM TẮT CUỐI CÙNG")
    print("="*80)

    total = len(df_cleaned)
    neg_count = len(df_negative)
    pos_count = len(df_positive)

    print(f"""
TỔNG QUAN:
   • Tổng reviews: {total:,}
   • Tiêu cực (1-3⭐): {neg_count:,} ({neg_count/total*100:.1f}%)
   • Tích cực (4-5⭐): {pos_count:,} ({pos_count/total*100:.1f}%)
""")

    print("="*80)
    print("HOÀN THÀNH!")
    print("="*80)

# ========================================
# BƯỚC 12: TÁCH TỪ TIẾNG VIỆT
# ========================================
print("\n" + "="*80)
print("BƯỚC 12: TÁCH TỪ TIẾNG VIỆT (WORD SEGMENTATION)")
print("="*80 + "\n")

from underthesea import word_tokenize

if 'df_cleaned' in locals() and 'content_cleaned' in df_cleaned.columns:
    print("Đang tách từ cho reviews...")
    df_cleaned['content_segmented'] = df_cleaned['content_cleaned'].apply(
        lambda x: word_tokenize(x, format="text") if isinstance(x, str) and x.strip() else ""
    )
    
    print("\nHoàn thành tách từ!")
    print("\nVí dụ trước và sau khi tách từ:")
    print("="*80)
    
    samples = df_cleaned[df_cleaned['content_cleaned'].str.len() > 20].sample(n=3)
    for idx, row in enumerate(samples.itertuples(), 1):
        print(f"\n[{idx}] TRƯỚC: {row.content_cleaned[:100]}")
        print(f"    SAU:   {row.content_segmented[:100]}")
    
    print("\n" + "="*80)

# ========================================
# BƯỚC 13: CHUẨN BỊ DỮ LIỆU CHO ML
# ========================================
print("\n" + "="*80)
print("BƯỚC 13: CHUẨN BỊ DỮ LIỆU CHO MACHINE LEARNING")
print("="*80 + "\n")

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from imblearn.over_sampling import RandomOverSampler

if 'df_cleaned' in locals():
    # Lọc reviews hợp lệ
    df_ml = df_cleaned[
        (df_cleaned['content_segmented'].notna()) & 
        (df_cleaned['content_segmented'].str.strip() != '') &
        (df_cleaned['sentiment_label'].notna())
    ].copy()
    
    print(f"Số lượng reviews hợp lệ: {len(df_ml):,}")
    print(f"\nPhân bố nhãn:")
    print(df_ml['sentiment_vi'].value_counts())
    
    # Tách train/test
    X = df_ml['content_segmented']
    y = df_ml['sentiment_label']
    
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    
    print(f"\n Train set: {len(X_train):,} reviews")
    print(f" Test set: {len(X_test):,} reviews")
    
    # Xử lý imbalance (nếu cần)
    print("\n Kiểm tra imbalance trong train set:")
    train_dist = pd.Series(y_train).value_counts()
    for label, count in train_dist.items():
        sentiment = 'Tiêu cực' if label == 0 else 'Tích cực'
        print(f"   {sentiment}: {count:,} ({count/len(y_train)*100:.1f}%)")
    
    # TF-IDF Vectorization
    print("\n Đang vectorize text với TF-IDF...")
    tfidf = TfidfVectorizer(
        max_features=5000,
        min_df=2,
        max_df=0.8,
        ngram_range=(1, 2),
        sublinear_tf=True
    )
    
    X_train_tfidf = tfidf.fit_transform(X_train)
    X_test_tfidf = tfidf.transform(X_test)
    
    print(f" TF-IDF matrix shape: {X_train_tfidf.shape}")
    print(f" Số lượng features: {len(tfidf.get_feature_names_out()):,}")
    
    print("\n" + "="*80)

# ========================================
# BƯỚC 14: XÂY DỰNG VÀ ĐÁNH GIÁ CÁC MÔ HÌNH ML
# ========================================
print("\n" + "="*80)
print("BƯỚC 14: XÂY DỰNG VÀ ĐÁNH GIÁ CÁC MÔ HÌNH ML")
print("="*80 + "\n")

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report, confusion_matrix
import time

if 'X_train_tfidf' in locals():
    # Dictionary để lưu kết quả
    results = {}
    trained_models = {}
    
    # Định nghĩa các mô hình
    models = {
        'Naive Bayes': MultinomialNB(alpha=1.0),
        'Logistic Regression': LogisticRegression(max_iter=1000, C=1.0, random_state=42),
        'SVM (Linear)': LinearSVC(max_iter=2000, C=1.0, random_state=42)
    }
    
    # Train và đánh giá từng mô hình
    for model_name, model in models.items():
        print(f"\n{'='*80}")
        print(f" TRAINING: {model_name}")
        print(f"{'='*80}")
        
        # Training
        start_time = time.time()
        model.fit(X_train_tfidf, y_train)
        train_time = time.time() - start_time
        
        # Prediction
        start_time = time.time()
        y_pred = model.predict(X_test_tfidf)
        pred_time = time.time() - start_time
        
        # Lưu model
        trained_models[model_name] = model
        
        # Tính toán metrics
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred, average='weighted')
        recall = recall_score(y_test, y_pred, average='weighted')
        f1 = f1_score(y_test, y_pred, average='weighted')
        
        results[model_name] = {
            'Accuracy': accuracy,
            'Precision': precision,
            'Recall': recall,
            'F1-Score': f1,
            'Training Time': train_time,
            'Prediction Time': pred_time
        }
        
        print(f"\n KẾT QUẢ:")
        print(f"   • Accuracy:  {accuracy:.4f}")
        print(f"   • Precision: {precision:.4f}")
        print(f"   • Recall:    {recall:.4f}")
        print(f"   • F1-Score:  {f1:.4f}")
        print(f"   • Training time: {train_time:.2f}s")
        print(f"   • Prediction time: {pred_time:.2f}s")
        
        print(f"\n CLASSIFICATION REPORT:")
        print(classification_report(y_test, y_pred, 
                                   target_names=['Tiêu cực', 'Tích cực'],
                                   digits=4))
        
        print(f"\n CONFUSION MATRIX:")
        cm = confusion_matrix(y_test, y_pred)
        print(f"   [[TN={cm[0,0]:4d}  FP={cm[0,1]:4d}]")
        print(f"    [FN={cm[1,0]:4d}  TP={cm[1,1]:4d}]]")
    
    print("\n" + "="*80)

# ========================================
# BƯỚC 15: SO SÁNH CÁC MÔ HÌNH
# ========================================
print("\n" + "="*80)
print("BƯỚC 15: SO SÁNH KẾT QUẢ CÁC MÔ HÌNH")
print("="*80 + "\n")

if 'results' in locals():
    # Tạo DataFrame so sánh
    comparison_df = pd.DataFrame(results).T
    comparison_df = comparison_df.round(4)
    
    print(" BẢNG SO SÁNH:")
    print("="*80)
    print(comparison_df.to_string())
    print("="*80)
    
    # Tìm mô hình tốt nhất
    best_model_name = comparison_df['F1-Score'].idxmax()
    best_f1 = comparison_df.loc[best_model_name, 'F1-Score']
    
    print(f"\n MÔ HÌNH TỐT NHẤT: {best_model_name}")
    print(f" F1-Score: {best_f1:.4f}")
    
    # Vẽ biểu đồ so sánh
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    
    # Biểu đồ 1: So sánh metrics
    metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
    x = np.arange(len(metrics))
    width = 0.25
    
    colors = ['#3b82f6', '#ef4444', '#10b981']
    for idx, (model_name, color) in enumerate(zip(results.keys(), colors)):
        values = [results[model_name][m] for m in metrics]
        axes[0].bar(x + idx*width, values, width, label=model_name, 
                   color=color, alpha=0.8, edgecolor='black', linewidth=1.5)
    
    axes[0].set_xlabel('Metrics', fontsize=12, fontweight='bold')
    axes[0].set_ylabel('Score', fontsize=12, fontweight='bold')
    axes[0].set_title('SO SÁNH HIỆU SUẤT CÁC MÔ HÌNH', fontsize=14, fontweight='bold', pad=15)
    axes[0].set_xticks(x + width)
    axes[0].set_xticklabels(metrics)
    axes[0].legend(loc='lower right')
    axes[0].grid(axis='y', alpha=0.3, linestyle='--')
    axes[0].set_ylim([0.5, 1.0])
    
    # Biểu đồ 2: So sánh thời gian
    model_names = list(results.keys())
    train_times = [results[m]['Training Time'] for m in model_names]
    pred_times = [results[m]['Prediction Time'] for m in model_names]
    
    x = np.arange(len(model_names))
    width = 0.35
    
    bars1 = axes[1].bar(x - width/2, train_times, width, label='Training Time',
                       color='#fb923c', alpha=0.8, edgecolor='black', linewidth=1.5)
    bars2 = axes[1].bar(x + width/2, pred_times, width, label='Prediction Time',
                       color='#a78bfa', alpha=0.8, edgecolor='black', linewidth=1.5)
    
    axes[1].set_xlabel('Models', fontsize=12, fontweight='bold')
    axes[1].set_ylabel('Time (seconds)', fontsize=12, fontweight='bold')
    axes[1].set_title('SO SÁNH THỜI GIAN TRAINING & PREDICTION', fontsize=14, fontweight='bold', pad=15)
    axes[1].set_xticks(x)
    axes[1].set_xticklabels(model_names, rotation=15, ha='right')
    axes[1].legend()
    axes[1].grid(axis='y', alpha=0.3, linestyle='--')
    
    # Thêm giá trị lên các cột
    for bars in [bars1, bars2]:
        for bar in bars:
            height = bar.get_height()
            axes[1].text(bar.get_x() + bar.get_width()/2., height,
                        f'{height:.3f}s',
                        ha='center', va='bottom', fontsize=9)
    
    plt.tight_layout()
    
    # Lưu biểu đồ
    chart_path = f'{DRIVE_FOLDER}/model_comparison.png'
    plt.savefig(chart_path, dpi=300, bbox_inches='tight')
    print(f"\n Đã lưu biểu đồ: model_comparison.png")
    plt.show()
    
    # Lưu kết quả so sánh
    comparison_df.to_csv(f'{DRIVE_FOLDER}/model_comparison.csv', encoding='utf-8-sig')
    print(f" Đã lưu: model_comparison.csv")
    
    print("\n" + "="*80)

# ========================================
# BƯỚC 16: PHÂN TÍCH CHI TIẾT THEO TỪNG NGÂN HÀNG
# ========================================
print("\n" + "="*80)
print("BƯỚC 16: PHÂN TÍCH CHI TIẾT THEO TỪNG NGÂN HÀNG")
print("="*80 + "\n")

if 'df_cleaned' in locals() and 'appId' in df_cleaned.columns:
    # Mapping tên ngân hàng
    app_names = {
        'com.vnpay.bidv': 'BIDV',
        'com.vnpay.Agribank3g': 'Agribank',
        'com.VCB': 'Vietcombank',
        'com.sacombank.ewallet': 'Sacombank',
        'com.mbmobile': 'MBBank',
        'com.vietinbank.ipay': 'VietinBank',
        'com.tpb.mb.gprsandroid': 'TPBank',
        'vn.com.techcombank.bb.app': 'Techcombank',
        'com.vnpay.hdbank': 'HDBank',
        'mobile.acb.com.vn': 'ACB',
        'vn.com.ocb.awe': 'OCB',
        'vn.com.msb.smartBanking': 'MSB'
    }
    
    df_cleaned['bank_name'] = df_cleaned['appId'].map(app_names)
    
    # Thống kê theo ngân hàng
    bank_stats = df_cleaned.groupby('bank_name').agg({
        'content': 'count',
        'score': 'mean',
        'sentiment_label': lambda x: (x == 1).sum() / len(x) * 100
    }).round(2)
    
    bank_stats.columns = ['Số reviews', 'Rating TB', '% Tích cực']
    bank_stats = bank_stats.sort_values('Rating TB', ascending=False)
    
    print(" THỐNG KÊ THEO NGÂN HÀNG:")
    print("="*80)
    print(bank_stats.to_string())
    print("="*80)
    
    # Vẽ biểu đồ
    fig, axes = plt.subplots(2, 1, figsize=(14, 10))
    
    # Biểu đồ 1: Rating trung bình
    banks = bank_stats.index
    ratings = bank_stats['Rating TB']
    colors = ['#22c55e' if r >= 4 else '#eab308' if r >= 3 else '#ef4444' for r in ratings]
    
    bars = axes[0].barh(banks, ratings, color=colors, alpha=0.8, edgecolor='black', linewidth=1.5)
    axes[0].set_xlabel('Rating Trung Bình', fontsize=12, fontweight='bold')
    axes[0].set_title('RATING TRUNG BÌNH THEO NGÂN HÀNG', fontsize=14, fontweight='bold', pad=15)
    axes[0].set_xlim([0, 5])
    axes[0].grid(axis='x', alpha=0.3, linestyle='--')
    
    for bar, rating in zip(bars, ratings):
        axes[0].text(rating + 0.1, bar.get_y() + bar.get_height()/2,
                    f'{rating:.2f}⭐',
                    va='center', fontsize=10, fontweight='bold')
    
    # Biểu đồ 2: % Tích cực
    positive_pct = bank_stats['% Tích cực']
    colors = ['#22c55e' if p >= 50 else '#ef4444' for p in positive_pct]
    
    bars = axes[1].barh(banks, positive_pct, color=colors, alpha=0.8, edgecolor='black', linewidth=1.5)
    axes[1].set_xlabel('% Reviews Tích Cực', fontsize=12, fontweight='bold')
    axes[1].set_title('TỶ LỆ REVIEWS TÍCH CỰC THEO NGÂN HÀNG', fontsize=14, fontweight='bold', pad=15)
    axes[1].set_xlim([0, 100])
    axes[1].grid(axis='x', alpha=0.3, linestyle='--')
    
    for bar, pct in zip(bars, positive_pct):
        axes[1].text(pct + 2, bar.get_y() + bar.get_height()/2,
                    f'{pct:.1f}%',
                    va='center', fontsize=10, fontweight='bold')
    
    plt.tight_layout()
    
    # Lưu biểu đồ
    chart_path = f'{DRIVE_FOLDER}/bank_comparison.png'
    plt.savefig(chart_path, dpi=300, bbox_inches='tight')
    print(f"\n Đã lưu biểu đồ: bank_comparison.png")
    plt.show()
    
    # Lưu thống kê
    bank_stats.to_csv(f'{DRIVE_FOLDER}/bank_statistics.csv', encoding='utf-8-sig')
    print(f" Đã lưu: bank_statistics.csv")
    
    print("\n" + "="*80)

# ========================================
# BƯỚC 17: LƯU MÔ HÌNH TỐT NHẤT
# ========================================
print("\n" + "="*80)
print("BƯỚC 17: LƯU MÔ HÌNH TỐT NHẤT")
print("="*80 + "\n")

import pickle

if 'trained_models' in locals() and 'best_model_name' in locals():
    best_model = trained_models[best_model_name]
    
    # Lưu model
    model_path = f'{DRIVE_FOLDER}/best_model.pkl'
    with open(model_path, 'wb') as f:
        pickle.dump(best_model, f)
    print(f" Đã lưu model: {best_model_name}")
    
    # Lưu vectorizer
    vectorizer_path = f'{DRIVE_FOLDER}/tfidf_vectorizer.pkl'
    with open(vectorizer_path, 'wb') as f:
        pickle.dump(tfidf, f)
    print(f" Đã lưu TF-IDF vectorizer")
    
    # Lưu metadata
    metadata = {
        'model_name': best_model_name,
        'f1_score': best_f1,
        'accuracy': results[best_model_name]['Accuracy'],
        'training_date': pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S'),
        'num_features': len(tfidf.get_feature_names_out()),
        'train_samples': len(X_train),
        'test_samples': len(X_test)
    }
    
    metadata_path = f'{DRIVE_FOLDER}/model_metadata.json'
    with open(metadata_path, 'w', encoding='utf-8') as f:
        json.dump(metadata, f, ensure_ascii=False, indent=2)
    print(f" Đã lưu metadata")
    
    print("\n" + "="*80)

# ========================================
# BƯỚC 18: TẠO WORD CLOUD
# ========================================
print("\n" + "="*80)
print("BƯỚC 18: TẠO WORD CLOUD")
print("="*80 + "\n")

from wordcloud import WordCloud

if 'df_cleaned' in locals():
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    
    # Word Cloud cho reviews tiêu cực
    negative_text = ' '.join(df_cleaned[df_cleaned['sentiment'] == 'negative']['content_segmented'].astype(str))
    
    wordcloud_neg = WordCloud(
        width=800, height=400,
        background_color='white',
        colormap='Reds',
        max_words=100,
        relative_scaling=0.5,
        min_font_size=10
    ).generate(negative_text)
    
    axes[0].imshow(wordcloud_neg, interpolation='bilinear')
    axes[0].set_title('WORD CLOUD - REVIEWS TIÊU CỰC', fontsize=14, fontweight='bold', pad=15)
    axes[0].axis('off')
    
    # Word Cloud cho reviews tích cực
    positive_text = ' '.join(df_cleaned[df_cleaned['sentiment'] == 'positive']['content_segmented'].astype(str))
    
    wordcloud_pos = WordCloud(
        width=800, height=400,
        background_color='white',
        colormap='Greens',
        max_words=100,
        relative_scaling=0.5,
        min_font_size=10
    ).generate(positive_text)
    
    axes[1].imshow(wordcloud_pos, interpolation='bilinear')
    axes[1].set_title('WORD CLOUD - REVIEWS TÍCH CỰC', fontsize=14, fontweight='bold', pad=15)
    axes[1].axis('off')
    
    plt.tight_layout()
    
    # Lưu biểu đồ
    chart_path = f'{DRIVE_FOLDER}/wordcloud.png'
    plt.savefig(chart_path, dpi=300, bbox_inches='tight')
    print(f" Đã lưu biểu đồ: wordcloud.png")
    plt.show()
    
    print("\n" + "="*80)

# ========================================
# BƯỚC 19: TÓM TẮT HOÀN CHỈNH
# ========================================
print("\n" + "="*80)
print("TÓM TẮT DỰ ÁN HOÀN CHỈNH")
print("="*80)

if 'df_cleaned' in locals() and 'results' in locals():
    print(f"""
📊 DỮ LIỆU:
   • Tổng số reviews: {len(df_cleaned):,}
   • Số ngân hàng: {df_cleaned['appId'].nunique()}
   • Reviews tiêu cực: {len(df_cleaned[df_cleaned['sentiment']=='negative']):,}
   • Reviews tích cực: {len(df_cleaned[df_cleaned['sentiment']=='positive']):,}

🤖 MÔ HÌNH MACHINE LEARNING:
   • Mô hình đã training: {len(results)}
   • Mô hình tốt nhất: {best_model_name}
   • F1-Score: {best_f1:.4f}
   • Accuracy: {results[best_model_name]['Accuracy']:.4f}

📁 FILES ĐÃ TẠO:
   • apps_info.csv - Thông tin ứng dụng
   • apps_reviews.csv - Reviews gốc
   • reviews_cleaned.csv - Reviews đã làm sạch
   • reviews_with_sentiment.csv - Reviews có nhãn sentiment
   • reviews_for_ml.csv - Dữ liệu cho ML
   • model_comparison.csv - So sánh các mô hình
   • bank_statistics.csv - Thống kê theo ngân hàng
   • best_model.pkl - Mô hình ML tốt nhất
   • tfidf_vectorizer.pkl - TF-IDF vectorizer
   • model_metadata.json - Metadata của mô hình

📈 BIỂU ĐỒ:
   • sentiment_distribution.png
   • model_comparison.png
   • bank_comparison.png
   • wordcloud.png

🎉 DỰ ÁN ĐÃ HOÀN THÀNH!
""")
    print("="*80)
    print("✨ BƯỚC TIẾP THEO: Xây dựng Web Dashboard với Streamlit")
    print("="*80)

